export const CREATE_PRIVATE_KEY = 'home/CREATE_PRIVATE_KEY';
export const CREATE_PRIVATE_KEY_SUCCESS = 'home/CREATE_PRIVATE_KEY_SUCCESS';
export const CREATE_PRIVATE_KEY_ERROR = 'home/CREATE_PRIVATE_KEY_ERROR';

export const ACCESS_WALLET = 'home/ACCESS_WALLET';
export const ACCESS_WALLET_SUCCESS = 'home/ACCESS_WALLET_SUCCESS';
export const ACCESS_WALLET_ERROR = 'home/ACCESS_WALLET_ERROR';

export const UPDATE_HOME_ALERT = 'home/UPDATE_HOME_ALERT';
